### ISSUE TITLE
Java outputs

### ISSUE THREAD

**Issue by axelay** [Braveno/cosigner#3]
This is what I get when I start the process using ```java -jar cosigner-core-0.0.1-SNAPSHOT.jar server core.yml```

Some of it I can work out but is it really necessary to output all of it? I tried to change settings in the core.yml but I cannot get rid of them. Please advise!

```
ERROR [2016-03-21 17:59:45,446] io.emax.cosigner.fiat.FiatWallet: Unable to create contract, FIAT module is not usable!
! java.net.ConnectException: Connection refused
! at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_72-internal]
! at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_72-internal]
! at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_72-internal]
! at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_72-internal]
! at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_72-internal]
! at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_72-internal]
! at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_72-internal]
! at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:146) ~[jsonrpc4j-9152cd0.jar:na]
! at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:242) ~[jsonrpc4j-9152cd0.jar:na]
! ... 14 common frames omitted
! Causing: java.lang.reflect.UndeclaredThrowableException: null
! at com.sun.proxy.$Proxy34.eth_getTransactionCount(Unknown Source) ~[na:na]
! at io.emax.cosigner.fiat.FiatWallet.getSigString(FiatWallet.java:408) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.getSigString(FiatWallet.java:362) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.signTransaction(FiatWallet.java:355) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.signTransaction(FiatWallet.java:317) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.setupFiatContract(FiatWallet.java:114) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.<init>(FiatWallet.java:62) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.core.CosignerApplication.run(CosignerApplication.java:89) [cosigner-core-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.core.CosignerApplication.run(CosignerApplication.java:26) [cosigner-core-0.0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:40) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.Application.run(Application.java:80) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.emax.cosigner.core.CosignerApplication.main(CosignerApplication.java:59) [cosigner-core-0.0.1-SNAPSHOT.jar:na]
ERROR [2016-03-21 17:59:45,457] io.emax.cosigner.fiat.FiatWallet: Unable to create contract, FIAT module is not usable!
! java.net.ConnectException: Connection refused
! at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_72-internal]
! at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_72-internal]
! at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_72-internal]
! at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_72-internal]
! at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_72-internal]
! at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_72-internal]
! at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[na:1.8.0_72-internal]
! at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999) ~[na:1.8.0_72-internal]
! at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933) ~[na:1.8.0_72-internal]
! at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:146) ~[jsonrpc4j-9152cd0.jar:na]
! at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:242) ~[jsonrpc4j-9152cd0.jar:na]
! ... 15 common frames omitted
! Causing: java.lang.reflect.UndeclaredThrowableException: null
! at com.sun.proxy.$Proxy34.eth_getTransactionCount(Unknown Source) ~[na:na]
! at io.emax.cosigner.fiat.FiatWallet.getSigString(FiatWallet.java:408) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.getSigString(FiatWallet.java:362) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.signTransaction(FiatWallet.java:355) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.signTransaction(FiatWallet.java:317) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.setupFiatContract(FiatWallet.java:114) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatWallet.<init>(FiatWallet.java:62) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.fiat.FiatMonitor.<init>(FiatMonitor.java:42) [cosigner-fiat-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.core.CosignerApplication.run(CosignerApplication.java:90) [cosigner-core-0.0.1-SNAPSHOT.jar:na]
! at io.emax.cosigner.core.CosignerApplication.run(CosignerApplication.java:26) [cosigner-core-0.0.1-SNAPSHOT.jar:na]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:40) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.Application.run(Application.java:80) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.emax.cosigner.core.CosignerApplication.main(CosignerApplication.java:59) [cosigner-core-0.0.1-SNAPSHOT.jar:na]
WARN  [2016-03-21 17:59:46,680] io.dropwizard.setup.AdminEnvironment:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    THIS APPLICATION HAS NO HEALTHCHECKS. THIS MEANS YOU WILL NEVER KNOW      !
!     IF IT DIES IN PRODUCTION, WHICH MEANS YOU WILL NEVER KNOW IF YOU'RE      !
!    LETTING YOUR USERS DOWN. YOU SHOULD ADD A HEALTHCHECK FOR EACH OF YOUR    !
!         APPLICATION'S DEPENDENCIES WHICH FULLY (BUT LIGHTLY) TESTS IT.       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by Dorgky** [comment]
The different currency modules will be loaded in a better way eventually. Right now, it loads all of them and those errors are just a result of the missing backends if you're not using them all. That said, the health check warning means it's started up and you can work with the server.

**Comment by trevorbernard** [comment]
@axelay You should be able to turn off logs levels per class with Dropwizard.

Something like this should work:

```yaml
logging:
  loggers:
    io.emax.cosigner.fiat.FiatWallet: OFF
```

**Comment by axelay** [comment]
```
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported format of logger 'io.emax.cosigner.fiat.FiatWallet'
        at io.dropwizard.logging.DefaultLoggingFactory.configureLoggers(DefaultLoggingFactory.java:197)
        at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:112)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:73)
        at io.dropwizard.cli.Cli.run(Cli.java:70)
        at io.dropwizard.Application.run(Application.java:80)
        at io.emax.cosigner.core.CosignerApplication.main(CosignerApplication.java:59)
```
Computer says no...

**Comment by axelay** [comment]
I get more output on the screen after the process started
```
Exception in thread "RxComputationThreadPool-1" Exception in thread "RxComputationThreadPool-2" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException
        at rx.Observable$27.onError(Observable.java:7923)
        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:146)
        at rx.internal.operators.OperatorOnErrorReturn$1.onNext(OperatorOnErrorReturn.java:65)
        at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
        at rx.Scheduler$Worker$1.call(Scheduler.java:120)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        ... 7 more
Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy34.eth_getTransactionCount(Unknown Source)
        at io.emax.cosigner.ethereum.EthereumWallet.syncMultiSigAddresses(EthereumWallet.java:86)
        at io.emax.cosigner.ethereum.EthereumWallet.lambda$static$0(EthereumWallet.java:55)
        at rx.Observable$27.onNext(Observable.java:7928)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
        ... 11 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:146)
        at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:242)
        ... 16 more
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException
        at rx.Observable$27.onError(Observable.java:7923)
        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:146)
        at rx.internal.operators.OperatorOnErrorReturn$1.onNext(OperatorOnErrorReturn.java:65)
        at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
        at rx.Scheduler$Worker$1.call(Scheduler.java:120)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        ... 7 more
Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy34.eth_blockNumber(Unknown Source)
        at io.emax.cosigner.ethereum.EthereumWallet.scanTransactions(EthereumWallet.java:901)
        at io.emax.cosigner.ethereum.EthereumWallet.lambda$static$1(EthereumWallet.java:62)
        at rx.Observable$27.onNext(Observable.java:7928)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
        ... 11 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:146)
        at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:242)
        ... 16 more
Exception in thread "RxComputationThreadPool-2" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException
        at rx.Observable$27.onError(Observable.java:7923)
        at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
        at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:146)
        at rx.internal.operators.OperatorOnErrorReturn$1.onNext(OperatorOnErrorReturn.java:65)
        at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
        at rx.Scheduler$Worker$1.call(Scheduler.java:120)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        ... 7 more
Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy34.eth_blockNumber(Unknown Source)
        at io.emax.cosigner.fiat.FiatWallet.scanTransactions(FiatWallet.java:456)
        at io.emax.cosigner.fiat.FiatWallet.lambda$static$0(FiatWallet.java:58)
        at rx.Observable$27.onNext(Observable.java:7928)
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
        ... 11 more
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at com.googlecode.jsonrpc4j.JsonRpcHttpClient.invoke(JsonRpcHttpClient.java:146)
        at com.googlecode.jsonrpc4j.ProxyUtil$3.invoke(ProxyUtil.java:242)
        ... 16 more
```

It seems to be still working but thought I'd bring that up to your attention.

**Comment by Dorgky** [comment]
Fixed with [PR 16](https://github.com/Braveno/cosigner/pull/16), disabling currencies that aren't used will prevent them from filling the logs with exceptions when they can't connect to their network nodes.
